services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${BACKEND}:/app
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:8080"
            #- "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm
        networks:
            - my-network

    php-fpm:
        container_name: php-fpm
        restart: always
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
            args:
                - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
                - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                - PHP_FPM_INSTALL_PDO_PGSQL=${PHP_FPM_INSTALL_PDO_PGSQL}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
        expose:
            - "9000"    
        volumes:
            - ${BACKEND}:/app
        networks:
            - my-network

    postgres:
        container_name: postgres
        restart: always
        build:
            context: ./postgres
            dockerfile: Dockerfile
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ${POSTGRES_DATA}:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        networks:
            - my-network

networks:
    my-network:
        driver: bridge